import esbuild from "esbuild";

const production = process.argv.includes("--production");
const watch = process.argv.includes("--watch");

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const esbuildConfig = {
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: ["obsidian", "electron", "@codemirror/autocomplete", "@codemirror/collab"],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  minify: production,
  outfile: "main.js",
  banner: {
    js: banner,
  },
};

if (watch) {
  const context = await esbuild.context(esbuildConfig);
  await context.watch();
  console.log("Watching for changes...");
} else {
  await esbuild.build(esbuildConfig);
  if (production) {
    console.log("Production build complete");
  }
}
